<!DOCTYPE html>
<html lang="en-us">
<head>

  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="theme" content="hugo-academic">
  <meta name="generator" content="Hugo 0.18.1" />
  <meta name="author" content="Chang Chen">
  <meta name="description" content="Biostatistics Master Student at Brown University">

  
  
  
  
    
    
    <link rel="stylesheet" href="/css/highlight.min.css">
    
  
  <link rel="stylesheet" href="/css/bootstrap.min.css">
  <link rel="stylesheet" href="/css/font-awesome.min.css">
  <link rel="stylesheet" href="/css/academicons.min.css">
  <link rel="stylesheet" href="//fonts.googleapis.com/css?family=Lato:400,700|Merriweather|Roboto+Mono">
  <link rel="stylesheet" href="/css/hugo-academic.css">
  

  <link rel="alternate" href="/index.xml" type="application/rss+xml" title="Chang Chen ScM">
  <link rel="feed" href="/index.xml" type="application/rss+xml" title="Chang Chen ScM">

  <link rel="icon" type="image/png" href="/img/icon.png">
  <link rel="apple-touch-icon" type="image/png" href="/img/apple-touch-icon.png">

  <link rel="canonical" href="/post/march-14-2017-pre-class/">

  

  <title>March 14, 2017 Pre-Class | Chang Chen ScM</title>

</head>
<body id="top" data-spy="scroll" data-target="#navbar-main" data-offset="71">

<nav class="navbar navbar-default navbar-fixed-top" id="navbar-main">
  <div class="container">

    
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse"
              data-target=".navbar-collapse" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/">Chang Chen ScM</a>
    </div>

    
    <div class="collapse navbar-collapse">

      
      <ul class="nav navbar-nav navbar-right">
        

        

        <li class="nav-item">
          <a href="/#about">
            
            <span>Home</span>
          </a>
        </li>

        
        

        

        <li class="nav-item">
          <a href="/#posts">
            
            <span>Posts</span>
          </a>
        </li>

        
        

        

        <li class="nav-item">
          <a href="/#projects">
            
            <span>Projects</span>
          </a>
        </li>

        
        

        

        <li class="nav-item">
          <a href="/#contact">
            
            <span>Contact</span>
          </a>
        </li>

        
        
      </ul>

    </div>
  </div>
</nav>


<article class="article" itemscope itemtype="http://schema.org/Article">

  

  <div class="article-container">
    <h1 itemprop="name">March 14, 2017 Pre-Class</h1>
    

<div class="article-metadata">

  <span class="article-date">
    <time datetime="2017-03-13 00:00:00 &#43;0000 UTC" itemprop="datePublished">
      Mon, Mar 13, 2017
    </time>
  </span>

  

  

  
  
<div class="share-box" aria-hidden="true">
  <ul class="share">
    <li>
      <a class="facebook"
         href="https://www.facebook.com/sharer.php?u=%2fpost%2fmarch-14-2017-pre-class%2f"
         target="_blank">
        <i class="fa fa-facebook"></i>
      </a>
    </li>
    <li>
      <a class="twitter"
         href="https://twitter.com/intent/tweet?text=March%2014%2c%202017%20Pre-Class&amp;url=%2fpost%2fmarch-14-2017-pre-class%2f"
         target="_blank">
        <i class="fa fa-twitter"></i>
      </a>
    </li>
    <li>
      <a class="linkedin"
         href="https://www.linkedin.com/shareArticle?mini=true&amp;url=%2fpost%2fmarch-14-2017-pre-class%2f&amp;title=March%2014%2c%202017%20Pre-Class"
         target="_blank">
        <i class="fa fa-linkedin"></i>
      </a>
    </li>
    <li>
      <a class="weibo"
         href="http://service.weibo.com/share/share.php?url=%2fpost%2fmarch-14-2017-pre-class%2f&amp;title=March%2014%2c%202017%20Pre-Class"
         target="_blank">
        <i class="fa fa-weibo"></i>
      </a>
    </li>
    <li>
      <a class="email"
         href="mailto:?subject=March%2014%2c%202017%20Pre-Class&amp;body=%2fpost%2fmarch-14-2017-pre-class%2f">
        <i class="fa fa-envelope"></i>
      </a>
    </li>
  </ul>
</div>


  

</div>

    <div class="article-style" itemprop="articleBody">
      <!-- BLOGDOWN-HEAD -->
<!-- /BLOGDOWN-HEAD -->

<!-- BLOGDOWN-BODY-BEFORE -->
<!-- /BLOGDOWN-BODY-BEFORE -->
<hr />
<style type="text/css">
.table {

    width: 80%;
    margin-left:10%; 
    margin-right:10%;
}
</style>
<div id="project-goals" class="section level1">
<h1>Project Goals:</h1>
<p>With this project we will simulate a famoues probability problem. This will not require knowledge of probability or statistics but only the logic to follow the steps in order to simulate this problem. This is one way to solve problems by using the computer.</p>
<div id="section" class="section level3">
<h3>1</h3>
<p><strong>Gambler’s Ruin</strong>: Suppose you have a bankroll of $1000 and make bets of $100 on a fair game. By simulating the outcome directly for at most 5000 iterations of the game (or hands), estimate: a. the probability that you have “busted” (lost all your money) by the time you have placed your one hundredth bet. b. the probability that you have busted by the time you have placed your five hundredth bet by simulating the outcome directly. c. the mean time you go bust, given that you go bust within the first 5000 hands. d. the mean and variance of your bankroll after 100 hands (including busts). e. the mean and variance of your bankroll after 500 hands (including busts).</p>
<p>Note: you <em>must</em> stop playing if your player has gone bust. How will you handle this in the <code>for</code> loop?</p>
</div>
<div id="for-this-project-i-use-the-original-meaning-of-gamblers-ruin-a-persistent-gambler-who-raises-his-bet-to-a-fixed-fraction-of-bankroll-when-he-wins-but-does-not-reduce-it-when-he-loses-will-eventually-and-inevitably-go-broke-even-if-he-has-a-positive-expected-value-on-each-bet." class="section level2">
<h2>For this project, I use the original meaning of gambler’s ruin: a persistent gambler who raises his bet to a fixed fraction of bankroll when he wins, but does not reduce it when he loses, will eventually and inevitably go broke, even if he has a positive expected value on each bet.</h2>
<div id="a" class="section level4">
<h4>(a)</h4>
<pre class="r"><code>library(epiDisplay)</code></pre>
<pre><code>## Loading required package: foreign</code></pre>
<pre><code>## Warning: package &#39;foreign&#39; was built under R version 3.2.5</code></pre>
<pre><code>## Loading required package: survival</code></pre>
<pre><code>## Loading required package: MASS</code></pre>
<pre><code>## Loading required package: nnet</code></pre>
<pre class="r"><code>GambRuinFunc=function(A,B,p)
{
  Rec=c(A)
  while(A&gt;0) {
    ProbVal=runif(1)
    if(ProbVal &lt;= p)
    {
      B = A+B
#A persistent gambler who raises his bet to a fixed fraction of bankroll when he wins
      A = (B+A)*0.1
    }else{
      B = B-A
#But does not reduce it when he loses
      A = A
      }
    Rec = c(Rec,A)
    if(B&lt;A){break}
  }
  Duration = length(Rec)
  return(Duration)
}
set.seed(1)
Durations = numeric()
M = 5000
for(i in 1:M)
{
  NextDuration = GambRuinFunc(A=100,B=900,p=0.5)
  Durations = c(Durations,NextDuration)
}
prob100&lt;-length(which(Durations&lt;=100))/5000
prob100</code></pre>
<pre><code>## [1] 0.119</code></pre>
<p>The probability that you have “busted” (lost all your money) by the time you have placed your one hundredth bet is 0.1192.</p>
</div>
<div id="b" class="section level4">
<h4>(b)</h4>
<pre class="r"><code>prob500&lt;-length(which(Durations&lt;=500))/5000
prob500</code></pre>
<pre><code>## [1] 0.477</code></pre>
<p>The probability that you have busted by the time you have placed your five hundredth bet by simulating the outcome directly is 0.4768.</p>
</div>
<div id="c" class="section level4">
<h4>(c)</h4>
<pre class="r"><code>d5000&lt;-Durations[which(Durations&lt;=5000)]
mean(d5000)</code></pre>
<pre><code>## [1] 759</code></pre>
<p>the mean time you go bust, given that you go bust within the first 5000 hand is 758.8801.</p>
</div>
<div id="d" class="section level4">
<h4>(d)</h4>
<pre class="r"><code>library(epiDisplay)
GambRuinFunc1=function(A,B,p)
{
  Rec=c(A)
  while(A&gt;0) {
    ProbVal=runif(1)
    if(ProbVal &lt;= p)
    {
      B = A+B
      A = (B+A)*0.1
    }else{
      B = B-A
      A = A
      }
    Rec = c(Rec,A)
    if(length(Rec)==100){break}
    if(B&lt;A){break}
  }
  Duration = length(Rec)
  return(B)
}
set.seed(1)
m100 = numeric()
M = 5000
for(i in 1:M)
{
  nextm = GambRuinFunc1(A=100,B=900,p=0.5)
  m100 = c(m100,nextm)
}
mean(m100)</code></pre>
<pre><code>## [1] 896</code></pre>
<pre class="r"><code>var(m100)</code></pre>
<pre><code>## [1] 2841197</code></pre>
<p>The mean of your bankroll after 100 hands (including busts) is 895.8597; The variance of your bankroll after 100 hands (including busts) is 2841197.</p>
</div>
<div id="e" class="section level4">
<h4>(e)</h4>
<pre class="r"><code>library(epiDisplay)
GambRuinFunc2=function(A,B,p)
{
  Rec=c(A)
  while(A&gt;0) {
    ProbVal=runif(1)
    if(ProbVal &lt;= p)
    {
      B = A+B
      A = (B+A)*0.1
    }else{
      B = B-A
      A = A
      }
    Rec = c(Rec,A)
    if(length(Rec)==500){break}
    if(B&lt;A){break}
  }
  Duration = length(Rec)
  return(B)
}
set.seed(1)
m500 = numeric()
M = 5000
for(i in 1:M)
{
  nextm = GambRuinFunc2(A=100,B=900,p=0.5)
  m500 = c(m500,nextm)
}
mean(m500)</code></pre>
<pre><code>## [1] 574</code></pre>
<pre class="r"><code>var(m500)</code></pre>
<pre><code>## [1] 30074552</code></pre>
<p>The mean of your bankroll after 500 hands (including busts) is 573.5246; The variance of your bankroll after 500 hands (including busts) is 30074552.</p>
</div>
<div id="section-1" class="section level3">
<h3>2</h3>
<p>Repeat the previous problem with betting on black in American roulette, where the probability of winning on any spin is 18/38 for an even payout.</p>
<div id="a-1" class="section level4">
<h4>(a)</h4>
<pre class="r"><code>library(epiDisplay)
GambRuinFunc=function(A,B,p)
{
  Rec=c(A)
  while(A&gt;0) {
    ProbVal=runif(1)
    if(ProbVal &lt;= p)
    {
      B = A+B
      A = (B+A)*0.1
    }else{
      B = B-A
      A = A
      }
    Rec = c(Rec,A)
    if(B&lt;A){break}
  }
  Duration = length(Rec)
  return(Duration)
}
set.seed(1)
Durations = numeric()
M = 5000
for(i in 1:M)
{
  NextDuration = GambRuinFunc(A=100,B=900,p=18/38)
  Durations = c(Durations,NextDuration)
}
prob100&lt;-length(which(Durations&lt;=100))/5000
prob100</code></pre>
<pre><code>## [1] 0.173</code></pre>
<p>The probability that you have “busted” (lost all your money) by the time you have placed your one hundredth bet is 0.173.</p>
</div>
<div id="b-1" class="section level4">
<h4>(b)</h4>
<pre class="r"><code>prob500&lt;-length(which(Durations&lt;=500))/5000
prob500</code></pre>
<pre><code>## [1] 0.63</code></pre>
<p>The probability that you have busted by the time you have placed your five hundredth bet by simulating the outcome directly is 0.6296.</p>
</div>
<div id="c-1" class="section level4">
<h4>(c)</h4>
<pre class="r"><code>d5000&lt;-Durations[which(Durations&lt;=5000)]
mean(d5000)</code></pre>
<pre><code>## [1] 505</code></pre>
<p>the mean time you go bust, given that you go bust within the first 5000 hand is 505.1114.</p>
</div>
<div id="d-1" class="section level4">
<h4>(d)</h4>
<pre class="r"><code>library(epiDisplay)
GambRuinFunc1=function(A,B,p)
{
  Rec=c(A)
  while(A&gt;0) {
    ProbVal=runif(1)
    if(ProbVal &lt;= p)
    {
      B = A+B
      A = (B+A)*0.1
    }else{
      B = B-A
      A = A
      }
    Rec = c(Rec,A)
    if(length(Rec)==100){break}
    if(B&lt;A){break}
  }
  Duration = length(Rec)
  return(B)
}
set.seed(1)
m100 = numeric()
M = 5000
for(i in 1:M)
{
  nextm = GambRuinFunc1(A=100,B=900,p=18/38)
  m100 = c(m100,nextm)
}
mean(m100)</code></pre>
<pre><code>## [1] 469</code></pre>
<pre class="r"><code>var(m100)</code></pre>
<pre><code>## [1] 849960</code></pre>
<p>The mean of your bankroll after 100 hands (including busts) is 469.1183; The variance of your bankroll after 100 hands (including busts) is 849960.</p>
</div>
<div id="e-1" class="section level4">
<h4>(e)</h4>
<pre class="r"><code>library(epiDisplay)
GambRuinFunc2=function(A,B,p)
{
  Rec=c(A)
  while(A&gt;0) {
    ProbVal=runif(1)
    if(ProbVal &lt;= p)
    {
      B = A+B
      A = (B+A)*0.1
    }else{
      B = B-A
      A = A
      }
    Rec = c(Rec,A)
    if(length(Rec)==500){break}
    if(B&lt;A){break}
  }
  Duration = length(Rec)
  return(B)
}
set.seed(1)
m500 = numeric()
M = 5000
for(i in 1:M)
{
  nextm = GambRuinFunc2(A=100,B=900,p=18/38)
  m500 = c(m500,nextm)
}
mean(m500)</code></pre>
<pre><code>## [1] 32.9</code></pre>
<pre class="r"><code>var(m500)</code></pre>
<pre><code>## [1] 95787</code></pre>
<p>The mean of your bankroll after 500 hands (including busts) is 32.88478; The variance of your bankroll after 500 hands (including busts) is 95786.5.</p>
</div>
</div>
<div id="section-2" class="section level3">
<h3>3</h3>
<p><strong>Markov Chains</strong>. Suppose you have a game where the probability of winning on your first hand is 48%; each time you win, that probability goes up by one percentage point for the next game (to a maximum of 100%, where it must stay), and each time you lose, it goes back down to 48%. Assume you cannot go bust and that the size of your wager is a constant $100.</p>
<div id="a-2" class="section level4">
<h4>(a)</h4>
<p>Is this a fair game? Simulate one hundred thousand sequential hands to determine the size of your return. Then repeat this simulation 99 more times to get a range of values to calculate the expectation.</p>
<pre class="r"><code>MCFunc=function(A,B,p)
{
  k=0
  prob&lt;-p
  while(A&gt;0) {
    ProbVal=runif(1)
    if(ProbVal &lt;= p)
    {
      B = B+A
      p = p+0.01
    }else{
      B = B-A
      p = prob
    }
    k=k+1
    if(k==100000){break}
    if(B&lt;A){break}
  }
  return(B)
}

size = numeric()
M = 100
for(i in 1:M)
{
  nextb = MCFunc(A=100,B=900,p=0.48)
  size = c(size,nextb)
}
mean(size)</code></pre>
<pre><code>## [1] 0</code></pre>
<p>The expectation of the size of return is 0, which means one will go busted after one hundred thousand sequential hands, so the game is not fair.</p>
</div>
<div id="b-2" class="section level4">
<h4>(b)</h4>
<p>Repeat this process but change the starting probability to a new value within 2% either way. Get the expected return after 100 repetitions. Keep exploring until you have a return value that is as fair as you can make it. Can you do this automatically?</p>
<pre class="r"><code>set.seed(1)
prop = numeric()
for (j in 1:20) {
size = numeric()
M = 100
for(i in 1:M)
{
  nextb = MCFunc(A=100,B=900,p=0.46+0.002*j)
  size = c(size,nextb)
}
nextprop = length(which(size==0))/100
prop&lt;-c(prop,nextprop)
}
prop</code></pre>
<pre><code>##  [1] 1.00 1.00 1.00 1.00 1.00 1.00 1.00 1.00 1.00 1.00 1.00 1.00 1.00 1.00
## [15] 0.96 0.94 0.88 0.80 0.71 0.67</code></pre>
<p>We found that if we choose the starting probability as 0.5, the proportion of size of return equals to 0 is closest to 0.5, which means the game is fairest under the starting probability of 0.5.</p>
</div>
<div id="c-2" class="section level4">
<h4>(c)</h4>
<p>Repeat again, keeping the initial probability at 48%, but this time change the probability increment to a value different from 1%. Get the expected return after 100 repetitions. Keep changing this value until you have a return value that is as fair as you can make it.</p>
<pre class="r"><code>MCFunc1=function(A,B,p,step)
{
  k=0
  prob&lt;-p
  while(A&gt;0) {
    ProbVal=runif(1)
    if(ProbVal &lt;= p)
    {
      B = B+A
      p = p+step
    }else{
      B = B-A
      p = prob
    }
    k=k+1
    if(k==100000){break}
    if(B&lt;A){break}
  }
  return(B)
}

set.seed(1)
prop = numeric()
for (j in 1:20) {
size = numeric()
M = 100
for(i in 1:M)
{
  nextb = MCFunc1(A=100,B=900,p=0.48,step=0.002*j)
  size = c(size,nextb)
}
nextprop = length(which(size==0))/100
prop&lt;-c(prop,nextprop)
}
prop</code></pre>
<pre><code>##  [1] 1.00 1.00 1.00 1.00 1.00 1.00 1.00 1.00 0.94 0.92 0.74 0.70 0.67 0.60
## [15] 0.57 0.57 0.50 0.39 0.38 0.34</code></pre>
<pre class="r"><code>0.002*17</code></pre>
<pre><code>## [1] 0.034</code></pre>
<p>We found that if we choose the probability increment to 0.034, the proportion of size of return equals to 0 is 0.5, which means the game is fair under the probability increment of 0.034.</p>
</div>
</div>
<div id="section-3" class="section level3">
<h3>4</h3>
<p>For the last two examples in the previous question, you calculated a mean value. Because you saved these final results in a vector, use the bootstrap to estimate the variance of the return in each case for your final answer. Once you have these results, which game has the smaller variance in returns?</p>
<div id="for-game-1-change-the-starting-probability" class="section level4">
<h4>For Game 1 (Change the starting probability)</h4>
<pre class="r"><code>bestp1&lt;-0.5
size1 = numeric()
M = 100
for(i in 1:M)
{
  nextb = MCFunc(A=100,B=900,p=bestp1)
  size1 = c(size1,nextb)
}
###Bootstrap
set.seed(1)
bs1&lt;-sample(size1,10000,replace = TRUE)
mean(bs1)</code></pre>
<pre><code>## [1] 56836</code></pre>
<pre class="r"><code>var(bs1)</code></pre>
<pre><code>## [1] 10785467594</code></pre>
</div>
<div id="for-game-2-change-the-probability-increment" class="section level4">
<h4>For Game 2 (Change the probability increment)</h4>
<pre class="r"><code>bestp2&lt;-0.034
size2 = numeric()
M = 100
for(i in 1:M)
{
  nextb = MCFunc1(A=100,B=900,p=0.48,step=bestp2)
  size2 = c(size2,nextb)
}
set.seed(1)
bs2&lt;-sample(size2,10000,replace = TRUE)
mean(bs2)</code></pre>
<pre><code>## [1] 5449959</code></pre>
<pre class="r"><code>var(bs2)</code></pre>
<pre><code>## [1] 2.47e+13</code></pre>
<pre class="r"><code>var(bs1)/var(bs2)</code></pre>
<pre><code>## [1] 0.000437</code></pre>
<p>The variance for game1 is 10785467594, the variance for game1 is 2.469009e+13. The proportion between the variance of two games’ sizes of return (0.0004368338) shows that the first game (Change the starting probability) has the smaller variance in returns.</p>
</div>
</div>
</div>
</div>

    </div>
  </div>

</article>

<div class="container">
  <nav>
  <ul class="pager">
    
    <li class="previous"><a href="/post/march-7-2017-in-class-project/"><span
      aria-hidden="true">&larr;</span> March 7, 2017 In-Class Project</a></li>
    

    
  </ul>
</nav>

</div>

<div class="article-container">
  
<section id="comments">
  <div id="disqus_thread"></div>
<script type="text/javascript">

(function() {
      
      
      if (window.location.hostname == "localhost")
                return;

      var dsq = document.createElement('script'); dsq.type = 'text/javascript'; dsq.async = true;
      var disqus_shortname = 'viccchen1991';
      dsq.src = 'https://' + disqus_shortname + '.disqus.com/embed.js';
      (document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0]).appendChild(dsq);
})();
</script>
<noscript>Please enable JavaScript to view the <a href="https://disqus.com/?ref_noscript">comments powered by Disqus.</a></noscript>
<a href="https://disqus.com/" class="dsq-brlink">comments powered by <span class="logo-disqus">Disqus</span></a>
</section>

</div>

<footer class="site-footer">
  <div class="container">
    <p class="powered-by">

      &copy; 2016 Your Name &middot; 

      Powered by the <a href="https://github.com/gcushen/hugo-academic" target="_blank">Academic
      theme</a> for <a href="http://gohugo.io" target="_blank">Hugo</a>.

      <span class="pull-right" aria-hidden="true">
        <a href="#" id="back_to_top">
          <span class="button_icon">
            <i class="fa fa-chevron-up fa-2x"></i>
          </span>
        </a>
      </span>

    </p>
  </div>
</footer>

    <script src="//cdnjs.cloudflare.com/ajax/libs/gsap/1.18.4/TweenMax.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/gsap/latest/plugins/ScrollToPlugin.min.js"></script>
    <script src="/js/jquery-1.12.3.min.js"></script>
    <script src="/js/bootstrap.min.js"></script>
    <script src="/js/isotope.pkgd.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/jquery.imagesloaded/4.1.1/imagesloaded.pkgd.min.js"></script>
    <script src="/js/hugo-academic.js"></script>
    

    

    
    
      
      <script src="//cdnjs.cloudflare.com/ajax/libs/highlight.js/9.9.0/highlight.min.js"></script>

      

      

      <script>hljs.initHighlightingOnLoad();</script>
    

    
    
    <script type="text/x-mathjax-config">
        MathJax.Hub.Config({ tex2jax: { inlineMath: [['$','$'], ['\\(','\\)']] } });
    </script>
    <script async src="//cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS_CHTML"></script>
    

  </body>
</html>

